### ISSUE TITLE
Testing with Angular 2 and Typescript.

### ISSUE THREAD

**Issue by TaranBarber** [mlaval/angular2-bootstrap#1]
Can you give me an quick explanation, or even a full-blown guide, on **running** your tests?  I have used jasmine and karma for javscript tests in the past. However I'm new to the Angular2 + Typescript environment, and I don't know how to properly run tests that import 'angular2/angular2' as a result.

Any help would be appreciated. Thanks!

**Comment by mlaval** [comment]
Hello,

running `gulp test` will "compile the project in the `dist/dev` folder. Compiling here means transpiling from Typescript to CommonJS, which is then loaded with System.js. It will then launch Karma on the files generated.
Basically, it follows what is done in https://github.com/angular/angular

Cheers

**Comment by TaranBarber** [comment]
Thanks for getting back to me so quickly.

When I try to build I get this error: 
>demo\samples\carousel\demo-carousel.ts(3,56): error TS2307: Cannot find external module 'carousel/carousel'.
>src\carousel\carousel.ts(104,25): error TS2339: Property '_results' does not exist on type 'QueryList<CarouselSlide>'.
>test\carousel\carousel_spec.ts(15,8): error TS2307: Cannot find external module 'angular2/test'.

Could commit more of your working directory folders, such as node_modules and typings folders? I'm afraid I don't have everything installed that I need.

**Comment by mlaval** [comment]
These errors are semantic errors raised by Typescript.
They don't prevent the build to be successful, nor the demo or the test to run.

You can ignore them, they will go away when angular2 will be more stabilized.
Keep in my mind that it is still in alpha and that this repo is quite experimental.

**Comment by TaranBarber** [comment]
oh! :smile:

I didn't realize it was working now. Thanks for the assistance.
