### ISSUE TITLE
Question: Bootstrap 3 or 4.alpha?

### ISSUE THREAD

**Issue by jimthedev** [mlaval/angular2-bootstrap#2]
Hi there, just a roadmap question. Do you think you'll be tracking against bootstrap 3 or bootstrap 4? The alpha of 4 was just released but I know this is a WIP so of course no pressure either way.

Thanks!

**Comment by mlaval** [comment]
I haven't had time to look at Bootstrap 4 yet, but it would make more sense to target it.
This repo is more a sandbox than a real project for now, so using Angular 2 alpha + Bootstrap 4 alpha would be the way to go ;)

**Comment by mlaval** [comment]
I'll keep this repo as a sandbox with BS3.
A proper Bootstrap support is on its way

**Comment by jimthedev** [comment]
@mlaval What do you mean proper bootstrap support is on its way?

**Comment by gdi2290** [comment]
https://github.com/valor-software/ng2-bootstrap supports 3 and 4 unless there is another project

**Comment by jimthedev** [comment]
Ok I knew about that project but wasn't sure if that was what he was talking about.
