### ISSUE TITLE
Carousel is Breaking on the Homepage

### ISSUE THREAD

**Issue by zamamohammed** [mlaval/angular2-bootstrap#4]
1. Go to http://mlaval.github.io/angular2-bootstrap/#/sample/carousel
2. Click on Alerts in the Navigation
3. Once on Alerts page, click on Carousel in the Navigation

Now you will see the images are not being displayed on Carousel.

**Comment by mlaval** [comment]
It is a known issue which was fixed in Angular 2: https://github.com/angular/angular/commit/01cdd3133959e3adc06ff5b479c395ea70fcc168
So it should be solved when integrating the next release of Angular 2 in this project.

**Comment by mlaval** [comment]
Solved by updating to alpha 40
